{% set name = "des-desimage" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/desimage/archive/refs/tags/{{ version }}.tar.gz
  sha256: bc0ed024b754e3f23cb9f77609ba14d9ad0b469724039c93120fa1cf7a71f173

build:
  skip: true  # [win]
  number: 0
  # this package uses the scripts argument in setuptools and so
  # cannot be noarch: python
  script:
    # I cannot get a patch to work so where we are
    # the next version won't need this so I put a version selector on it
    - cp ${RECIPE_DIR}/setup.py.new ${SRC_DIR}/setup.py  # [version == '0.9.0']
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - fitsio
    - pillow
    - numba

test:
  imports:
    - desimage

about:
  home: https://github.com/esheldon/desimage
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Code to make pretty pictures from DES coadd images

extra:
  recipe-maintainers:
    - beckermr
